name: "JSON Patch"
description: "Apply a JSON Patch to a given file"
inputs:
  patches:
    description: JSON or YAML object of RFC6902 patches keyed by file paths.
    required: true

runs:
  using: composite
  steps:
    - name: Install JSON Patch
      shell: bash
      run: npm --no-save install fast-json-patch yaml

    - name: Patch Config
      uses: actions/github-script@v6
      env:
        PATCHES: ${{ inputs.patches }}
      with:
        script: |
          const { PATCHES } = process.env;
          let patches;
          try {
            patches = JSON.parse(PATCHES);
          } catch(e) {
            core.info('Failed to parse as json, attempting yaml...')
            const yaml = require('yaml');
            patches = yaml.parse(PATCHES);
          }
          const fs = require('fs/promises');
          const jsonPatch = require('fast-json-patch')
          core.info('Parsed input:');
          core.info(JSON.stringify(patches, null, 2));
          
          const promises = Object.entries(patches).map(async ([filePath, patches]) => {
            core.info(`Applying patches to ${filePath}:`)
            core.info(JSON.stringify(patches, null, 2))
            const data = JSON.parse((await fs.readFile(filePath)).toString())
            const newData = jsonPatch.applyPatch(data, patches).newDocument;
            await fs.writeFile(filePath, JSON.stringify(newData, null, 2))
          });
          await Promise.all(promises);
          core.info('All patches applied!');
          
