name: "JSON Patch"
description: "Apply a JSON Patch to a given file"
inputs:
  file-path:
    description: Path to file to patch.
    required: true
  patches:
    description: YAML string array of patches to apply.
    required: true

runs:
  using: composite
  steps:
    - name: Install JSON Patch
      shell: bash
      run: npm install fast-json-patch yaml

    - name: Patch Config
      uses: actions/github-script@v6
      env:
        TARGET: ${{ inputs.file-path }}
        PATCHES: ${{ inputs.patches }}
      with:
        script: |
          const fs = require('fs/promises');
          const yaml = require('yaml');
          const jsonPatch = require('fast-json-patch')
          const { TARGET, PATCHES } = process.env;
          const patches = yaml.parse(PATCHES)
          core.info(`Applying patches to ${TARGET}:`)
          core.info(JSON.stringify(patches, null, 2))
          const data = JSON.parse((await fs.readFile(TARGET)).toString())
          const newData = jsonPatch.applyPatch(data, patches).newDocument;
          await fs.writeFile(TARGET, JSON.stringify(newData, null, 2))
