name: Update Config
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        type: string
      path:
        description: "JSON Patch Path"
        required: true
        type: string
      value:
        description: "New value"
        required: true
        type: string

  workflow_call:
    inputs:
      environment:
        description: "Target environment"
        required: true
        type: string
      path:
        description: "JSON Patch Path"
        required: true
        type: string
      value:
        description: "New value"
        required: true
        type: string

jobs:
  update:
    name: Patch // ${{ inputs.environment }}
    runs-on: ubuntu-latest
    env:
      REPO_PATH: .crisiscleanup-configs
      TARGET: api/${{ inputs.environment }}.json
      JSON_PATH: ${{ inputs.path }}
      NEW_VALUE: ${{ inputs.value }}
    steps:
      # ensure we checkout the configs repo during a workflow_call event.
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
          token: ${{ secrets.GH_CONFIGS_RO_PAT }}
          repository: CrisisCleanup/configs
          ref: main
          path: ${{ env.REPO_PATH }}
          clean: false

      - name: Install JSON Patch
        run: npm install fast-json-patch

      - name: Patch Config
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs/promises')
            const path = require('path')
            const jsonPatch = require('fast-json-patch')
            const { TARGET, JSON_PATH, NEW_VALUE, REPO_PATH } = process.env;
            const filePath = path.join(REPO_PATH, TARGET)
            const patch = [
              { op: "replace", path: JSON_PATH, value: NEW_VALUE }
            ]
            const data = JSON.parse((await fs.readFile(filePath)).toString())
            const newData = jsonPatch.applyPatch(data, patch).newDocument;
            await fs.writeFile(filePath, JSON.stringify(newData, null, 2))

      - name: Authenticate Bot
        id: auth
        uses: CrisisCleanup/crisiscleanup-3-api/.github/actions/auth-gha-app@master
        with:
          app_id: ${{ secrets.CCU_BOT_APP_ID }}
          install_id: ${{ secrets.CCU_BOT_INSTALL_ID }}
          private_key: ${{ secrets.CCU_BOT_PRIVATE_KEY }}
          authenticate: "true"

      - name: Commit changes.
        run: |
          git config --global user.name "${{ steps.auth.outputs.name }}"
          git config --global user.email "${{ steps.auth.outputs.email }}"
          git add ${{ env.TARGET }}
          git commit -m "chore(${{ inputs.environment }}): update config ${{ inputs.path }}" || true

      - name: Push Changes
        uses: ad-m/github-push-action@c361e2bb0747df3110bdbe051b209b40766670ec
        with:
          github_token: ${{ steps.auth.outputs.token }}
          branch: main
          repository: CrisisCleanup/configs

      - name: Cleanup
        if: always()
        continue-on-error: true
        run: rm -rf ${{ env.REPO_PATH }} || true
